package objectorientedconcepts;

public class Assignment5 {
    // CREATE A CLASS CALLED AS RESTAURANT
    // CREATE STRING ARRAY WHICH STORES EMPLOYEE NAMES
    // CREATE STRING ARRAY WHICH STORES DISHES
    // CREATE INT ARRAY WHICH STORES PRICES
    // ON CREATING A RESTAURANT OBJECT YOU MENU WITH DISHES SHOULD AUTOMATICALLY
    // SHOW
    // CREATE A METHOD TO PLACE ORDER FOR A DISH WHICH IS TAKEN BY AN EMPLOYEE
}
