package objectorientedconcepts;

public class Assignment3 {
    // DECLARE A BLUEPRINT / CLASS CALLED AS CAR
    // DECLARE PROPERTIES
    // DECLARE NEW INSTANCE OF THE BLUEPRINT
    // ASSIGN DIFFERENT VALUES TO THE BLUEPRINT INSTANCE
    // PRINT THE VALUES TO CONSOLE
    // IF POSSSIBLE, DECLARE A METHOD AND EXECUTE
}
